/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Memory = IDL.Record({
  'id' : IDL.Nat64,
  'created' : IDL.Int,
  'text' : IDL.Text,
  'author' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Opt(IDL.Text),
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const SubmitMemoryResponse = IDL.Variant({
  'ok' : Memory,
  'err' : IDL.Record({ 'message' : IDL.Text }),
});

export const idlService = IDL.Service({
  'getAllMemories' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
  'getMemory' : IDL.Func([IDL.Nat64], [IDL.Opt(Memory)], ['query']),
  'submitMemory' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [SubmitMemoryResponse],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Memory = IDL.Record({
    'id' : IDL.Nat64,
    'created' : IDL.Int,
    'text' : IDL.Text,
    'author' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Opt(IDL.Text),
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const SubmitMemoryResponse = IDL.Variant({
    'ok' : Memory,
    'err' : IDL.Record({ 'message' : IDL.Text }),
  });
  
  return IDL.Service({
    'getAllMemories' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
    'getMemory' : IDL.Func([IDL.Nat64], [IDL.Opt(Memory)], ['query']),
    'submitMemory' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [SubmitMemoryResponse],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };