/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'created' : bigint,
  'displayName' : string,
  'text' : string,
  'sender' : Principal,
}
export interface Memory {
  'id' : bigint,
  'created' : bigint,
  'submitter' : [] | [Principal],
  'edited' : [] | [bigint],
  'text' : string,
  'author' : string,
  'imageUrl' : [] | [string],
  'videoUrl' : [] | [string],
}
export interface Song {
  'title' : [] | [string],
  'year' : [] | [bigint],
  'description' : [] | [string],
  'fileName' : string,
  'artist' : [] | [string],
  'bytes' : Uint8Array,
}
export type SubmitMemoryResponse = { 'ok' : Memory } |
  { 'err' : { 'message' : string } };
export type SubmitMessageResponse = { 'ok' : ChatMessage } |
  { 'err' : { 'message' : string } };
export interface UserProfile { 'displayName' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface YouTubeLink { 'url' : string, 'timestamp' : bigint }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteChatMessages' : ActorMethod<[BigUint64Array], undefined>,
  'editMemory' : ActorMethod<
    [bigint, string, string, [] | [string], [] | [string]],
    SubmitMemoryResponse
  >,
  'getAllMemories' : ActorMethod<[], Array<Memory>>,
  'getAllSongs' : ActorMethod<[], Array<[bigint, Song]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMemory' : ActorMethod<[bigint], [] | [Memory]>,
  'getMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getMessagesByPrincipal' : ActorMethod<[Principal], Array<ChatMessage>>,
  'getMessagesBySender' : ActorMethod<[Principal], Array<ChatMessage>>,
  'getMessagesFromTo' : ActorMethod<
    [Principal, bigint, bigint],
    Array<ChatMessage>
  >,
  'getSong' : ActorMethod<[bigint], [] | [Song]>,
  'getUniqueSenders' : ActorMethod<[], Array<Principal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getYouTubeLinks' : ActorMethod<[], Array<YouTubeLink>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitMemory' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    SubmitMemoryResponse
  >,
  'submitMessage' : ActorMethod<[string, string], SubmitMessageResponse>,
  'submitYouTubeLink' : ActorMethod<[string], boolean>,
  'uploadSong' : ActorMethod<
    [
      Uint8Array,
      string,
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [string],
    ],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];